# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        # dostęp do formularza logowania
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # cała sekcja /admin tylko dla admina
        - { path: ^/admin, roles: ROLE_ADMIN }

        # CRUD przepisów tylko dla admina
        - { path: ^/recipe/new,      roles: ROLE_ADMIN }
        - { path: ^/recipe/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/recipe/\d+$,     methods: [POST], roles: ROLE_ADMIN }

        # CRUD kategorii tylko dla admina
        - { path: ^/category/new,      roles: ROLE_ADMIN }
        - { path: ^/category/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/category/\d+$,     methods: [POST], roles: ROLE_ADMIN }

        # usuwanie komentarzy tylko przez admina
        - { path: ^/comment/\d+/delete, roles: ROLE_ADMIN }
